export const TRENDS = [
  {
    id: "quiet-luxury",
    name: "Quiet Luxury",
    icon: "diamond",
    color: "#8B7355",
    blurb: "Understated, expensive-looking neutrals — cashmere tones, camel, ivory and black.",
    families: ["neutral", "warm", "black", "white", "muted-warm"],
    palette: ["#f5f0e6", "#b99b6b", "#3d3d3d", "#1a1a1a"],
  },
  {
    id: "monochrome",
    name: "Monochrome",
    icon: "filter_b_and_w",
    color: "#2f2f2f",
    blurb: "One color head-to-toe — the cleanest, most editorial way to dress.",
    families: ["red", "blue", "warm", "green", "purple", "pink", "teal", "yellow", "muted-warm"],
    palette: ["#111111", "#f5f5f5", "#7a7a7a"],
  },
  {
    id: "old-money",
    name: "Old Money Preppy",
    icon: "anchors",
    color: "#1f4e5f",
    blurb: "Navy, white, khaki and denim — classic collegiate staples that never date.",
    families: ["neutral", "blue", "white", "warm"],
    palette: ["#1f4e5f", "#ffffff", "#c3b091", "#1560bd"],
  },
  {
    id: "streetwear",
    name: "Streetwear",
    icon: "sports_esports",
    color: "#1a1a1a",
    blurb: "Black-heavy utility and denim with a bold accent — effortless urban energy.",
    families: ["black", "neutral", "denim", "green", "red"],
    palette: ["#111111", "#1560bd", "#4c6b4f", "#e11"],
  },
  {
    id: "y2k",
    name: "Y2K Dopamine",
    icon: "auto_awesome",
    color: "#c84fb0",
    blurb: "Pastels, brights and color-blocking — playful retro-futurism seen on every feed.",
    families: ["pink", "purple", "blue", "yellow", "teal", "white"],
    palette: ["#ffc0cb", "#b49be8", "#89cff0", "#ffe066"],
  },
  {
    id: "coastal",
    name: "Coastal Linen",
    icon: "beach_access",
    color: "#3e7c86",
    blurb: "White, beige and light-wash linen vibes — breezy vacation dressing gone mainstream.",
    families: ["white", "neutral", "teal", "blue", "warm"],
    palette: ["#ffffff", "#f5f5dc", "#a8d5d5", "#c2b280"],
  },
  {
    id: "dark-academia",
    name: "Dark Academia",
    icon: "menu_book",
    color: "#4a3b2f",
    blurb: "Browns, black, olive and wine — layered, scholarly and moody.",
    families: ["warm", "black", "neutral", "green", "red"],
    palette: ["#3b2f2a", "#8b4513", "#4a3b2f", "#722f37"],
  },
  {
    id: "minimal",
    name: "Capsule Minimal",
    icon: "checkroom",
    color: "#5a5a5a",
    blurb: "Black, white, gray and denim — a foolproof 10-piece rotation.",
    families: ["black", "white", "neutral", "denim"],
    palette: ["#111111", "#ffffff", "#9c9c9c", "#1560bd"],
  },
  {
    id: "evening",
    name: "Night Out",
    icon: "nightlife",
    color: "#2d2d3f",
    blurb: "Black, wine, purple and gold — polished and confident after dark.",
    families: ["black", "red", "purple", "white", "warm"],
    palette: ["#111111", "#722f37", "#4b0082", "#d4af37"],
  },
  {
    id: "streetwear-color",
    name: "Bold Color Pop",
    icon: "palette",
    color: "#d9534f",
    blurb: "Neutrals grounded by one loud accent — the easiest way to wear color.",
    families: ["neutral", "black", "white", "red", "yellow", "pink", "teal"],
    palette: ["#333333", "#e4572e", "#ffe066", "#1560bd"],
  },
];
